export const PATTERNS_PAGE_SIZE = 30;
export const PATTERNS_SCANNER_INTERVAL_MS = 60_000;
export const PATTERNS_FRONTEND_POLL_MS = 45_000;
export const PATTERN_CANDLE_LIMIT = 300;
export const PATTERN_MIN_QUALITY = 55;
export const PATTERN_FINISHED_RETENTION_MS = 15 * 60_000;
